spring:
  flyway:
    enabled: true

app:
  course:
    repository: jdbc
  identity:
    repository: jdbc
  enrollment:
    repository: jdbc
  learning-progress:
    repository: jdbc
  grading:
    repository: jdbc
  certificate:
    repository: jdbc
  job-orchestrator:
    repository: jdbc
    scheduler:
      enabled: true
      fixed-delay-ms: 5000
  notification:
    repository: jdbc
