spring:
  flyway:
    enabled: true

app:
  course:
    repository: jdbc
  identity:
    repository: jdbc
  enrollment:
    repository: jdbc
  learning-progress:
    repository: jdbc
  grading:
    repository: jdbc
  certificate:
    repository: jdbc
  job-orchestrator:
    repository: jdbc
  notification:
    repository: jdbc
