name: Javascript tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

jobs:
  frontend_tests:
    name: studio-dashboard-tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20]

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup npm
        run: npm i -g npm@10.7.x

      - name: Install npm
        run: npm ci  

      - name: Install Studio Dashboard dependencies
        run: npm --prefix frontend-app-studio-dashboard ci

      - name: Run Frontend Tests
        run: |
          npm run test
